version: '3.9'

services:
  auth:
    build:
      context: ./services/auth
    container_name: auth-service
    ports:
      - "5001:8000"
  users:
    build:
      context: ./services/users
    container_name: users-service
    ports:
      - "5002:8000"
  suppliers:
    build:
      context: ./services/suppliers
    container_name: suppliers-service
    ports:
      - "5003:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: supplierdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: